//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace VINASIC.Object
{
    public partial class T_ErrorLog
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string ModuleName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
        public bool IsFix { get; set; }
        public string ErrorCaption { get; set; }
        public string ErrorClass { get; set; }
        public string ErrorMethod { get; set; }
        public string StrackTrace { get; set; }
        public string IpError { get; set; }
        public string ActionError { get; set; }
        public string TargetSite { get; set; }
    }
    
}
