//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace VINASIC.Object
{
    public partial class T_MenuCategory
    {
        public T_MenuCategory()
        {
            this.T_Menu = new Collection<T_Menu>();
        }
    
        public int Id { get; set; }
        public string Category { get; set; }
        public string Position { get; set; }
        public int OrderIndex { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public bool IsViewIcon { get; set; }
        public string Link { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
    
        public virtual Collection<T_Menu> T_Menu { get; set; }
    }
    
}
