//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace VINASIC.Object
{
    public partial class T_Position
    {
        public T_Position()
        {
            this.T_Staff = new Collection<T_Staff>();
            this.T_User = new Collection<T_User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OrganizationId { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual T_Organization T_Organization { get; set; }
        public virtual Collection<T_Staff> T_Staff { get; set; }
        public virtual Collection<T_User> T_User { get; set; }
    }
    
}
