//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace VINASIC.Object
{
    public partial class T_StockIn
    {
        public T_StockIn()
        {
            this.T_StockInDetail = new Collection<T_StockInDetail>();
        }
    
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> StockInDate { get; set; }
        public double SubTotal { get; set; }
        public bool IsPayment { get; set; }
        public bool IsApproval { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Description { get; set; }
    
        public virtual T_Partner T_Partner { get; set; }
        public virtual Collection<T_StockInDetail> T_StockInDetail { get; set; }
    }
    
}
