//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace VINASIC.Object
{
    public partial class T_StockInDetail
    {
        public int Id { get; set; }
        public int StockInId { get; set; }
        public int MaterialId { get; set; }
        public double Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public double SubTotal { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> Index { get; set; }
        public string MateriaName { get; set; }
    
        public virtual T_Material T_Material { get; set; }
        public virtual T_StockIn T_StockIn { get; set; }
    }
    
}
