//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace VINASIC.Object
{
    public partial class T_User
    {
        public T_User()
        {
            this.T_OrderDetail = new Collection<T_OrderDetail>();
            this.T_OrderDetail1 = new Collection<T_OrderDetail>();
            this.T_UserFormular = new Collection<T_UserFormular>();
            this.T_Order = new Collection<T_Order>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public bool IsLock { get; set; }
        public bool IsRequireChangePW { get; set; }
        public bool IsForgotPassword { get; set; }
        public string NoteForgotPassword { get; set; }
        public string Email { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> LockedTime { get; set; }
        public string LastName { get; set; }
        public string FisrtName { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsOwner { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public int PositionId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string Address { get; set; }
        public string ColorString { get; set; }
    
        public virtual T_Position T_Position { get; set; }
        public virtual Collection<T_OrderDetail> T_OrderDetail { get; set; }
        public virtual Collection<T_OrderDetail> T_OrderDetail1 { get; set; }
        public virtual Collection<T_UserFormular> T_UserFormular { get; set; }
        public virtual Collection<T_Order> T_Order { get; set; }
    }
    
}
